### ISSUE TITLE
Local and Netlify builds are FAILING due to svelte-motion...

### ISSUE THREAD

**Issue by rchrdnsh** [micha-lmxt/svelte-motion#12]
I'm trying to build my sveltekit app and it's failing locally and on netlify with the following errors related to svelte-motion:

```bash
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-netlify
 > .svelte-kit/output/server/chunks/__layout-1e3255ca.js:10:7: warning: Ignoring this import because "node_modules/popmotion/dist/es/index.js" was marked as having no side effects
    10 │ import "popmotion";
       ╵        ~~~~~~~~~~~
   node_modules/popmotion/package.json:17:4: note: "sideEffects" is false in the enclosing "package.json" file
    17 │     "sideEffects": false,
       ╵     ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/__layout-1e3255ca.js:11:7: warning: Ignoring this import because "node_modules/style-value-types/dist/es/index.js" was marked as having no side effects
    11 │ import "style-value-types";
       ╵        ~~~~~~~~~~~~~~~~~~~
   node_modules/style-value-types/package.json:18:2: note: "sideEffects" is false in the enclosing "package.json" file
    18 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-f5a6e348.js:64:7: warning: Ignoring this import because "node_modules/popmotion/dist/es/index.js" was marked as having no side effects
    64 │ import "popmotion";
       ╵        ~~~~~~~~~~~
   node_modules/popmotion/package.json:17:4: note: "sideEffects" is false in the enclosing "package.json" file
    17 │     "sideEffects": false,
       ╵     ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-f5a6e348.js:65:7: warning: Ignoring this import because "node_modules/style-value-types/dist/es/index.js" was marked as having no side effects
    65 │ import "style-value-types";
       ╵        ~~~~~~~~~~~~~~~~~~~
   node_modules/style-value-types/package.json:18:2: note: "sideEffects" is false in the enclosing "package.json" file
    18 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-9e379867.js:34:7: warning: Ignoring this import because "node_modules/popmotion/dist/es/index.js" was marked as having no side effects
    34 │ import "popmotion";
       ╵        ~~~~~~~~~~~
   node_modules/popmotion/package.json:17:4: note: "sideEffects" is false in the enclosing "package.json" file
    17 │     "sideEffects": false,
       ╵     ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-9e379867.js:35:7: warning: Ignoring this import because "node_modules/style-value-types/dist/es/index.js" was marked as having no side effects
    35 │ import "style-value-types";
       ╵        ~~~~~~~~~~~~~~~~~~~
   node_modules/style-value-types/package.json:18:2: note: "sideEffects" is false in the enclosing "package.json" file
    18 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-1863fd49.js:65:7: warning: Ignoring this import because "node_modules/popmotion/dist/es/index.js" was marked as having no side effects
    65 │ import "popmotion";
       ╵        ~~~~~~~~~~~
   node_modules/popmotion/package.json:17:4: note: "sideEffects" is false in the enclosing "package.json" file
    17 │     "sideEffects": false,
       ╵     ~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/index-1863fd49.js:66:7: warning: Ignoring this import because "node_modules/style-value-types/dist/es/index.js" was marked as having no side effects
    66 │ import "style-value-types";
       ╵        ~~~~~~~~~~~~~~~~~~~
   node_modules/style-value-types/package.json:18:2: note: "sideEffects" is false in the enclosing "package.json" file
    18 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~

file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/.svelte-kit/output/server/chunks/MotionSSR-5f759e16.js:6
import { number, px, degrees, scale, alpha, progressPercentage, complex, color, filter, percent, vw, vh } from "style-value-types";
                                     ^^^^^
SyntaxError: Named export 'alpha' not found. The requested module 'style-value-types' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'style-value-types';
const { number, px, degrees, scale, alpha, progressPercentage, complex, color, filter, percent, vw, vh } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:121:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:171:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.load_component (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/.svelte-kit/output/server/chunks/app-33a853a6.js:531:13)
    at async Promise.all (index 0)
    at async respond$1 (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1211:11)
    at async render_page (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1454:19)
    at async resolve (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1717:10)
    at async respond (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async visit (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:167:20)
SyntaxError: Named export 'alpha' not found. The requested module 'style-value-types' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'style-value-types';
const { number, px, degrees, scale, alpha, progressPercentage, complex, color, filter, percent, vw, vh } = pkg;

> 500 /
Error: 500 /
    at file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
    at visit (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:222:5)
    at async prerender (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:303:6)
    at async Object.prerender (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:368:4)
    at async adapt (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/adapter-netlify/index.js:48:4)
    at async adapt (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/chunks/index4.js:393:2)
    at async file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/@sveltejs/kit/dist/cli.js:896:5
```

...I'm trying to figure out what's going on but really have no idea at the moment...

**Comment by rchrdnsh** [comment]
I'm going to close this out for now, as the project currently builds, but I get other errors and issues that I will bring up in another issue or two :-)
