### ISSUE TITLE
New breaking error with latest kit and vite 4.0.0...

### ISSUE THREAD

**Issue by rchrdnsh** [micha-lmxt/svelte-motion#28]
### to the latest kit and vite (1.0.0-next.581 for kit and 4.0.0 for vite) and getting the following breaking error:

```js
Cannot read properties of undefined (reading '__assign')
TypeError: Cannot read properties of undefined (reading '__assign')
    at /node_modules/svelte-motion/node_modules/popmotion/node_modules/style-value-types/dist/es/numbers/index.js:9:12
    at async instantiateModule (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:53246:9)
```
...dunno what's going on, but it the site updates are out of commission until this can be resolved.

**Comment by rchrdnsh** [comment]
hmmm...wondering if popmotion needs to updated to a more recent version? it's on 11.0.5 but the version in the svelte-motion package.json is 9.3.5...I figure you are aware of that, but maybe something has been updated since then that might affect this error?

**Comment by rchrdnsh** [comment]
another update...pushed it to github and it built and runs in production...just totally broken in dev.

**Comment by rchrdnsh** [comment]
got another one tonight trying to re-install the library:

```js
Cannot read properties of undefined (reading 'linear')
TypeError: Cannot read properties of undefined (reading 'linear')
    at /node_modules/svelte-motion/src/animation/utils/easing.js:12:12
    at async instantiateModule (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:53246:9)
```
...which seems to be a similar type of issue, just with something different. Maybe it's due to Vite 4.0.0 switching to Rollup 3.something...

**Comment by rchrdnsh** [comment]
gonna try and make a minrep of this...

**Comment by rchrdnsh** [comment]
k, here is the minrep:

https://github.com/rchrdnsh/motion-issue

simply a skeleton kit project with the latest kit and vite, with only one `<Motion>` component imported into only one `+page.svelte`

same error message...

**Comment by micha-lmxt** [comment]
Thank you for the repo and the efforts. I've updated the version of popmotion and framesync. Building works for me now. For dev, tslib seems to be in a format, which vite 4 currently does not like. 
Bloody workaround is to go into node_modules/tslib:
1. Add 'type':'module' in package.json
2. In tslib/modules/index.js change first line to ˋimport * as tslib from '../tslib.js'ˋ

Hope this helps.

**Comment by rchrdnsh** [comment]
yay, thank you, I got it working now as well...

Was looking at the tslib package file and noticed this:

```json
"exports": {
        ".": {
            "module": "./tslib.es6.js",
            "import": "./modules/index.js",
            "default": "./tslib.js"
        },
        "./*": "./*",
        "./": "./"
    }
```

...maybe there is a way of specifying ESM vs CJS or soemthing when importing from the lib? I don't understand this stuff very much, tho...
